### ISSUE TITLE
Kernel 4.1.4 error

### ISSUE THREAD

**Issue by williambout** [pimoroni/unicorn-hat#32]
I recently upgraded to kernel 4.1.4 and neopixel seems broken.

```
Traceback (most recent call last):
  File "light.py", line 4, in <module>
    import unicornhat as unicorn
  File "/usr/local/lib/python2.7/dist-packages/unicornhat.py", line 13, in <module>
    ws2812.begin()
  File "/usr/local/lib/python2.7/dist-packages/neopixel.py", line 107, in begin
    raise RuntimeError('ws2811_init failed with code {0}'.format(resp))
RuntimeError: ws2811_init failed with code -1
```

name -a :
`Linux jesse 4.1.4+ #808 PREEMPT Thu Aug 6 15:51:03 BST 2015 armv6l GNU/Linux`

**Comment by williambout** [comment]
Fixed with 5c03f81b72eb2e44c58f850db4e3fad90dc3d7a7
