### ISSUE TITLE
kernel 4.1.6+ error with a cc1: error: unrecognized command line option ‘-fstack-protector-strong’

### ISSUE THREAD

**Issue by alexej-okelloj** [pimoroni/unicorn-hat#33]
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 4.1.6+ #810 PREEMPT Tue Aug 18 15:19:58 BST 2015 armv6l GNU/Linux
Log is below:
pi@raspberrypi ~ $ sudo pip install unicornhat
Requirement already satisfied (use --upgrade to upgrade): unicornhat in /usr/local/lib/python2.7/dist-packages/unicornhat-2.0.2-py2.7.egg
Downloading/unpacking rpi-ws281x>=1.0.1 (from unicornhat)
  Downloading rpi_ws281x-1.2.0.tar.gz (123kB): 123kB downloaded
  Running setup.py (path:/tmp/pip-build-34DjBZ/rpi-ws281x/setup.py) egg_info for package rpi-ws281x
    
Installing collected packages: rpi-ws281x
  Running setup.py install for rpi-ws281x
    Compiling ws281x library...
    building '_rpi_ws281x' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilib/ -I/usr/include/python2.7 -c rpi_ws281x_wrap.c -o build/temp.linux-armv6l-2.7/rpi_ws281x_wrap.o
    cc1: error: unrecognized command line option ‘-fstack-protector-strong’
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-34DjBZ/rpi-ws281x/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NOHEAg-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

Compiling ws281x library...

creating build

creating build/lib.linux-armv6l-2.7

copying neopixel.py -> build/lib.linux-armv6l-2.7

running build_ext

building '_rpi_ws281x' extension

creating build/temp.linux-armv6l-2.7

arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Ilib/ -I/usr/include/python2.7 -c rpi_ws281x_wrap.c -o build/temp.linux-armv6l-2.7/rpi_ws281x_wrap.o

cc1: error: unrecognized command line option ‘-fstack-protector-strong’

error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-34DjBZ/rpi-ws281x/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-NOHEAg-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-34DjBZ/rpi-ws281x
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 248, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 49: ordinal not in range(128)

**Comment by alexej-okelloj** [comment]
solved by upgrading gcc to 4.9, see thread https://stackoverflow.com/questions/27182042/pip-error-unrecognized-command-line-option-fstack-protector-strong
