### ISSUE TITLE
Unicornhat via cgi Webinterface

### ISSUE THREAD

**Issue by johnsmith87** [pimoroni/unicorn-hat#42]
Calling import unicornhat as www-data will result in following:

www-data@raspberrypi:~/Pimoroni/unicornhat$ python simple.py
Failed to open /dev/vcio, trying old method.
Failed to create mailbox device /dev/mailbox-679: Permission denied
Failed to open /dev/vcio, trying old method.
Failed to create mailbox device /dev/mailbox-679: Permission denied
Failed to open /dev/vcio, trying old method.
Failed to create mailbox device /dev/mailbox-679: Permission denied
Traceback (most recent call last):
  File "simple.py", line 3, in <module>
    import unicornhat as UH
  File "/usr/local/lib/python2.7/dist-packages/unicornhat.py", line 13, in <module>
    ws2812.begin()
  File "/usr/local/lib/python2.7/dist-packages/neopixel.py", line 107, in begin
    raise RuntimeError('ws2811_init failed with code {0}'.format(resp))
RuntimeError: ws2811_init failed with code -1
Segmentation fault

How would you be able to execute python scripts via www-data (i.e. cgi webserver script)

Want to code a mood light with web interface for choosing color.

Any help will be appreciated.

Thanks

**Comment by johnsmith87** [comment]
Nevermind. Found another solution. Modified the unicornprint thingy. Utilized Flask and used another colorpicker & jquery-ajax to generate get urls
